/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.lifealert;

public final class R {
    public static final class array {
        public static final int sensitivities=0x7f050000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int sensitivity_bar_0=0x7f06000b;
        public static final int sensitivity_bar_1=0x7f06000a;
        public static final int sensitivity_bar_10=0x7f060001;
        public static final int sensitivity_bar_2=0x7f060009;
        public static final int sensitivity_bar_3=0x7f060008;
        public static final int sensitivity_bar_4=0x7f060007;
        public static final int sensitivity_bar_5=0x7f060006;
        public static final int sensitivity_bar_6=0x7f060005;
        public static final int sensitivity_bar_7=0x7f060004;
        public static final int sensitivity_bar_8=0x7f060003;
        public static final int sensitivity_bar_9=0x7f060002;
        public static final int sensitivity_bar_inactive=0x7f060000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int alert_okay_button=0x7f080000;
        public static final int alert_timeleft=0x7f080001;
        public static final int config_activiate=0x7f080014;
        public static final int config_call911=0x7f08000c;
        public static final int config_emergencyAddr=0x7f080009;
        public static final int config_emergencyEmail=0x7f08000b;
        public static final int config_emergencyInfo=0x7f080007;
        public static final int config_emergencyName=0x7f080008;
        public static final int config_emergencyPhone=0x7f08000a;
        public static final int config_sensitivity=0x7f080010;
        public static final int config_sensitivity_status=0x7f080011;
        public static final int config_status=0x7f080013;
        public static final int config_statusColor=0x7f080012;
        public static final int config_textMsg=0x7f08000d;
        public static final int config_userAddr=0x7f080004;
        public static final int config_userEmail=0x7f080006;
        public static final int config_userInfo=0x7f080002;
        public static final int config_userName=0x7f080003;
        public static final int config_userPhone=0x7f080005;
        public static final int config_voiceMail=0x7f08000e;
        public static final int config_voiceMailStatus=0x7f08000f;
        public static final int main_text=0x7f080015;
        public static final int sensitivity_bar_0=0x7f080026;
        public static final int sensitivity_bar_1=0x7f080025;
        public static final int sensitivity_bar_10=0x7f080018;
        public static final int sensitivity_bar_2=0x7f080024;
        public static final int sensitivity_bar_3=0x7f080022;
        public static final int sensitivity_bar_4=0x7f080021;
        public static final int sensitivity_bar_5=0x7f08001f;
        public static final int sensitivity_bar_6=0x7f08001e;
        public static final int sensitivity_bar_7=0x7f08001c;
        public static final int sensitivity_bar_8=0x7f08001b;
        public static final int sensitivity_bar_9=0x7f080019;
        public static final int sensitivity_normal=0x7f08001d;
        public static final int sensitivity_notsensitive=0x7f080017;
        public static final int sensitivity_sensitive=0x7f080020;
        public static final int sensitivity_somewhat=0x7f08001a;
        public static final int sensitivity_status=0x7f080028;
        public static final int sensitivity_testagain=0x7f080029;
        public static final int sensitivity_verysensitive=0x7f080023;
        public static final int statusColor=0x7f080027;
        public static final int text1=0x7f080016;
    }
    public static final class layout {
        public static final int alert=0x7f030000;
        public static final int configuration=0x7f030001;
        public static final int main=0x7f030002;
        public static final int notes_row=0x7f030003;
        public static final int select_emergency=0x7f030004;
        public static final int sensitivity=0x7f030005;
    }
    public static final class raw {
        public static final int alertvoice=0x7f040000;
    }
    public static final class string {
        public static final int alert_are_you_okay=0x7f07002b;
        public static final int alert_okay_notification=0x7f070030;
        public static final int alert_please_press_button=0x7f07002c;
        public static final int alert_second=0x7f07002f;
        public static final int alert_will_call_msg=0x7f07002e;
        public static final int alert_yes=0x7f07002d;
        public static final int app_name=0x7f070000;
        public static final int call_emergency=0x7f070001;
        public static final int config_call911=0x7f070014;
        public static final int config_emergencyaddr_hint=0x7f070011;
        public static final int config_emergencyemail_hint=0x7f070013;
        public static final int config_emergencyinfo=0x7f07000f;
        public static final int config_emergencyname_hint=0x7f070010;
        public static final int config_emergencyphone_hint=0x7f070012;
        public static final int config_is_incomplete=0x7f070022;
        public static final int config_sensitivity=0x7f07001a;
        public static final int config_sensitivity_status=0x7f07001b;
        public static final int config_systemaction_activate=0x7f07001f;
        public static final int config_systemaction_deactivate=0x7f070020;
        public static final int config_systemstatus=0x7f07001c;
        public static final int config_systemstatus_active=0x7f07001d;
        public static final int config_systemstatus_inactive=0x7f07001e;
        public static final int config_textmsg=0x7f070015;
        public static final int config_textmsg_hint=0x7f070016;
        public static final int config_useraddr_hint=0x7f07000c;
        public static final int config_useremail_hint=0x7f07000e;
        public static final int config_userinfo=0x7f07000a;
        public static final int config_username_hint=0x7f07000b;
        public static final int config_userphone_hint=0x7f07000d;
        public static final int config_voicemsg=0x7f070017;
        public static final int config_voicemsg_norecorded=0x7f070019;
        public static final int config_voicemsg_recorded=0x7f070018;
        public static final int confirm_emergency_contact=0x7f070005;
        public static final int email_emergency=0x7f070003;
        public static final int intro_greeting=0x7f070008;
        public static final int monitor_life=0x7f070004;
        public static final int no_emergency_contact=0x7f070006;
        public static final int notification_no_voicemail=0x7f070021;
        public static final int phone_Number_911=0x7f070009;
        public static final int select_emergency=0x7f070002;
        public static final int selected_emergency_contact=0x7f070007;
        public static final int sensitivity_normal=0x7f070025;
        public static final int sensitivity_notsensitive=0x7f070023;
        public static final int sensitivity_sensitive=0x7f070026;
        public static final int sensitivity_somewhat=0x7f070024;
        public static final int sensitivity_testagain=0x7f070029;
        public static final int sensitivity_testing_insession=0x7f07002a;
        public static final int sensitivity_teststatus_ok=0x7f070028;
        public static final int sensitivity_verysensitive=0x7f070027;
    }
}
